[mysqld]
# set basedir to your installation path
basedir=C:\\opt\\mysql
# set datadir to the location of your data directory
datadir=C:\\data\\mysql

# https://dev.mysql.com/doc/refman/8.4/en/caching-sha2-pluggable-authentication.html
caching_sha2_password_private_key_path=C:\\data\\mysql\\private_key.pem
caching_sha2_password_public_key_path=C:\\data\\mysql\\public_key.pem

# default: 3306
# port=3306
