<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>Tutorial1</StartupObject>
    <NuGetAuditMode>all</NuGetAuditMode>
    <GeneratePackageOnBuild>False</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.10" />
    <PackageReference Include="System.Security.Permissions" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="MySql.Data">
      <HintPath>$(CNET_HOME)\MySql.Data.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
